### ISSUE TITLE
  Getting CTD when reading a book or spell tome

### ISSUE THREAD

**Issue by slacksystem** [alandtse/po3-Tweaks#1]
Hi I'm running a slightly modified Auriel's Dream list ([https://modwat.ch/u/SlackSystem/](https://modwat.ch/u/SlackSystem/)). po3 Tweaks VR is overwriting po3 tweaks, the script files are there, the default ini from po3 tweaks (which updated itself with the new optiosn for VR) the dll and pdb, both from the VR version. When I load the game with the tweaks enabled, any time I try to read a spell tome or book, I get a CTD. When I load it without the tweaks enabled, I don't have the issue

[Here](https://pastebin.com/EExB1EmN) is the most recent crash log from crashloggervr (thanks for that mod too)

Please let me know if there is any more info I can provide that might help.

**Comment by alandtse** [comment]
Does it stop crashing if you disable the 'Can't Be Taken Book' Flag?

**Comment by alandtse** [comment]
Also, do any of the other mods you have modify books or their flags? The specific item at issue is a book being created by synthesis. The crash doesn't make sense because it's just checking to make sure there's a book which clearly exists in the crashlog.

**Comment by alandtse** [comment]
Oh, try the new release first before doing anything else.

**Comment by slacksystem** [comment]
None of those options worked until I updated Address Library as well as po3 tweaks. Now it works great!
