### ISSUE TITLE
Scripts from SSE version

### ISSUE THREAD

**Issue by naqaden** [alandtse/po3-Tweaks#2]
As of 1.7.5, [powerofthree's Tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/51073?tab=files) doesn't have scripts. Do we no longer need the original mod, or should we use an older version of it?

**Comment by alandtse** [comment]
Po3 forgot to package them. Follow whatever advice he suggests whether grabbing the original scripts or waiting for a new build.

**Comment by naqaden** [comment]
Thanks, I see [that](https://forums.nexusmods.com/index.php?/topic/10143368-powerofthrees-tweaks/page-74#entry116416938) now. Upon closer inspection, there's only 1 script with 1 basic line in it, unchanged since its inclusion in SSE 1.6.0. For now I'll just use the script from 1.7.1 as other commenters are doing.
